// <auto-generated />
using System;
using EquillibriumERP.Manufacturing.Infrastructure.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace EquillibriumERP.Manufacturing.Migrations
{
    [DbContext(typeof(ManufacturingDbContext))]
    [Migration("20260708103344_RemoveBomName")]
    partial class RemoveBomName
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.7")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("EquillibriumERP.Manufacturing.Domain.Entities.BOMStep", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("BillOfMaterialId")
                        .HasColumnType("uuid");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("DurationMinutes")
                        .HasColumnType("integer");

                    b.Property<decimal>("QuantityPercentage")
                        .HasPrecision(18, 4)
                        .HasColumnType("numeric(18,4)");

                    b.Property<Guid?>("RawMaterialProductId")
                        .HasColumnType("uuid");

                    b.Property<int>("Status")
                        .HasColumnType("integer");

                    b.Property<int>("StepNumber")
                        .HasColumnType("integer");

                    b.Property<int>("Type")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("BillOfMaterialId");

                    b.HasIndex("BillOfMaterialId", "StepNumber")
                        .IsUnique();

                    b.ToTable("BOMSteps", (string)null);
                });

            modelBuilder.Entity("EquillibriumERP.Manufacturing.Domain.Entities.BOMStepMaterial", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("BOMStepId")
                        .HasColumnType("uuid");

                    b.Property<decimal>("Quantity")
                        .HasPrecision(18, 4)
                        .HasColumnType("numeric(18,4)");

                    b.Property<Guid>("RawMaterialProductId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("BOMStepId");

                    b.HasIndex("RawMaterialProductId");

                    b.ToTable("BOMStepMaterials", (string)null);
                });

            modelBuilder.Entity("EquillibriumERP.Manufacturing.Domain.Entities.BillOfMaterial", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<Guid>("ProductId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("Code")
                        .IsUnique();

                    b.HasIndex("ProductId");

                    b.ToTable("BillOfMaterials", (string)null);
                });

            modelBuilder.Entity("EquillibriumERP.Manufacturing.Domain.Entities.BillOfMaterialItem", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("BillOfMaterialId")
                        .HasColumnType("uuid");

                    b.Property<decimal>("Quantity")
                        .HasPrecision(18, 4)
                        .HasColumnType("numeric(18,4)");

                    b.Property<Guid>("RawMaterialProductId")
                        .HasColumnType("uuid");

                    b.Property<string>("UnitOfMeasure")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.HasKey("Id");

                    b.HasIndex("BillOfMaterialId");

                    b.HasIndex("RawMaterialProductId");

                    b.ToTable("BillOfMaterialItems", (string)null);
                });

            modelBuilder.Entity("EquillibriumERP.Manufacturing.Domain.Entities.MaterialConsumption", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("ConsumedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("LotNumber")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<decimal>("Quantity")
                        .HasPrecision(18, 4)
                        .HasColumnType("numeric(18,4)");

                    b.Property<Guid>("RawMaterialProductId")
                        .HasColumnType("uuid");

                    b.Property<string>("UnitOfMeasure")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<Guid>("WorkOrderId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("WorkOrderStepId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("LotNumber");

                    b.HasIndex("RawMaterialProductId");

                    b.HasIndex("WorkOrderId");

                    b.HasIndex("WorkOrderStepId");

                    b.ToTable("MaterialConsumptions", (string)null);
                });

            modelBuilder.Entity("EquillibriumERP.Manufacturing.Domain.Entities.ProductBatch", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("BatchNumber")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("ProductId")
                        .HasColumnType("uuid");

                    b.Property<decimal>("QuantityProduced")
                        .HasPrecision(18, 4)
                        .HasColumnType("numeric(18,4)");

                    b.Property<Guid>("WorkOrderId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("BatchNumber");

                    b.HasIndex("WorkOrderId");

                    b.ToTable("ProductBatches", (string)null);
                });

            modelBuilder.Entity("EquillibriumERP.Manufacturing.Domain.Entities.StepMaterialConsumption", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<decimal>("QuantityUsed")
                        .HasPrecision(18, 4)
                        .HasColumnType("numeric(18,4)");

                    b.Property<Guid>("RawMaterialProductId")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("RecordedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("WorkOrderStepId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("RawMaterialProductId");

                    b.HasIndex("WorkOrderStepId");

                    b.ToTable("StepMaterialConsumptions", (string)null);
                });

            modelBuilder.Entity("EquillibriumERP.Manufacturing.Domain.Entities.WorkOrder", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("BatchNo")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<Guid>("BillOfMaterialId")
                        .HasColumnType("uuid");

                    b.Property<DateTime?>("CompletedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("LotNo")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<decimal>("PlannedQuantity")
                        .HasPrecision(18, 4)
                        .HasColumnType("numeric(18,4)");

                    b.Property<int>("Status")
                        .HasColumnType("integer");

                    b.Property<string>("UnitOfMeasure")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.HasKey("Id");

                    b.HasIndex("BatchNo");

                    b.HasIndex("BillOfMaterialId");

                    b.HasIndex("LotNo");

                    b.HasIndex("Status");

                    b.ToTable("WorkOrders", (string)null);
                });

            modelBuilder.Entity("EquillibriumERP.Manufacturing.Domain.Entities.WorkOrderMaterial", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<decimal>("ConsumedQuantity")
                        .HasPrecision(18, 4)
                        .HasColumnType("numeric(18,4)");

                    b.Property<decimal>("ExpectedQuantity")
                        .HasPrecision(18, 4)
                        .HasColumnType("numeric(18,4)");

                    b.Property<decimal>("IssuedQuantity")
                        .HasPrecision(18, 4)
                        .HasColumnType("numeric(18,4)");

                    b.Property<Guid>("RawMaterialProductId")
                        .HasColumnType("uuid");

                    b.Property<string>("UnitOfMeasure")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<Guid>("WorkOrderId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("RawMaterialProductId");

                    b.HasIndex("WorkOrderId");

                    b.ToTable("WorkOrderMaterials", (string)null);
                });

            modelBuilder.Entity("EquillibriumERP.Manufacturing.Domain.Entities.WorkOrderStep", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Action")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid>("BOMProcessStepId")
                        .HasColumnType("uuid");

                    b.Property<DateTime?>("CompletedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("StartedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("Status")
                        .HasColumnType("integer");

                    b.Property<int>("StepNumber")
                        .HasColumnType("integer");

                    b.Property<Guid>("WorkOrderId")
                        .HasColumnType("uuid");

                    b.Property<Guid?>("WorkOrderMaterialId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("BOMProcessStepId");

                    b.HasIndex("WorkOrderId");

                    b.HasIndex("WorkOrderMaterialId");

                    b.HasIndex("WorkOrderId", "StepNumber")
                        .IsUnique();

                    b.ToTable("WorkOrderSteps", (string)null);
                });

            modelBuilder.Entity("EquillibriumERP.Manufacturing.Domain.Entities.WorkOrderTransaction", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<decimal>("ActualQuantity")
                        .HasPrecision(18, 4)
                        .HasColumnType("numeric(18,4)");

                    b.Property<string>("Comment")
                        .HasColumnType("text");

                    b.Property<DateTime>("ExecutedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("ExecutedByUserId")
                        .HasColumnType("uuid");

                    b.Property<decimal>("ExpectedQuantity")
                        .HasPrecision(18, 4)
                        .HasColumnType("numeric(18,4)");

                    b.Property<string>("RawMaterialLotNo")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("UnitOfMeasure")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<Guid>("WorkOrderId")
                        .HasColumnType("uuid");

                    b.Property<Guid?>("WorkOrderMaterialId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("WorkOrderStepId")
                        .HasColumnType("uuid");

                    b.Property<string>("Workstation")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.HasKey("Id");

                    b.HasIndex("ExecutedAt");

                    b.HasIndex("WorkOrderId");

                    b.HasIndex("WorkOrderMaterialId");

                    b.HasIndex("WorkOrderStepId");

                    b.ToTable("WorkOrderTransactions", (string)null);
                });

            modelBuilder.Entity("EquillibriumERP.Manufacturing.Domain.Entities.BOMStep", b =>
                {
                    b.HasOne("EquillibriumERP.Manufacturing.Domain.Entities.BillOfMaterial", null)
                        .WithMany("Steps")
                        .HasForeignKey("BillOfMaterialId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("EquillibriumERP.Manufacturing.Domain.Entities.BillOfMaterialItem", b =>
                {
                    b.HasOne("EquillibriumERP.Manufacturing.Domain.Entities.BillOfMaterial", "BillOfMaterial")
                        .WithMany("Items")
                        .HasForeignKey("BillOfMaterialId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("BillOfMaterial");
                });

            modelBuilder.Entity("EquillibriumERP.Manufacturing.Domain.Entities.MaterialConsumption", b =>
                {
                    b.HasOne("EquillibriumERP.Manufacturing.Domain.Entities.WorkOrder", "WorkOrder")
                        .WithMany("MaterialConsumptions")
                        .HasForeignKey("WorkOrderId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("EquillibriumERP.Manufacturing.Domain.Entities.WorkOrderStep", "WorkOrderStep")
                        .WithMany()
                        .HasForeignKey("WorkOrderStepId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("WorkOrder");

                    b.Navigation("WorkOrderStep");
                });

            modelBuilder.Entity("EquillibriumERP.Manufacturing.Domain.Entities.ProductBatch", b =>
                {
                    b.HasOne("EquillibriumERP.Manufacturing.Domain.Entities.WorkOrder", "WorkOrder")
                        .WithMany("ProductBatches")
                        .HasForeignKey("WorkOrderId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("WorkOrder");
                });

            modelBuilder.Entity("EquillibriumERP.Manufacturing.Domain.Entities.WorkOrder", b =>
                {
                    b.HasOne("EquillibriumERP.Manufacturing.Domain.Entities.BillOfMaterial", "BillOfMaterial")
                        .WithMany()
                        .HasForeignKey("BillOfMaterialId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("BillOfMaterial");
                });

            modelBuilder.Entity("EquillibriumERP.Manufacturing.Domain.Entities.WorkOrderMaterial", b =>
                {
                    b.HasOne("EquillibriumERP.Manufacturing.Domain.Entities.WorkOrder", "WorkOrder")
                        .WithMany("Materials")
                        .HasForeignKey("WorkOrderId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("WorkOrder");
                });

            modelBuilder.Entity("EquillibriumERP.Manufacturing.Domain.Entities.WorkOrderStep", b =>
                {
                    b.HasOne("EquillibriumERP.Manufacturing.Domain.Entities.WorkOrder", "WorkOrder")
                        .WithMany("Steps")
                        .HasForeignKey("WorkOrderId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("EquillibriumERP.Manufacturing.Domain.Entities.WorkOrderMaterial", "WorkOrderMaterial")
                        .WithMany()
                        .HasForeignKey("WorkOrderMaterialId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("WorkOrder");

                    b.Navigation("WorkOrderMaterial");
                });

            modelBuilder.Entity("EquillibriumERP.Manufacturing.Domain.Entities.BillOfMaterial", b =>
                {
                    b.Navigation("Items");

                    b.Navigation("Steps");
                });

            modelBuilder.Entity("EquillibriumERP.Manufacturing.Domain.Entities.WorkOrder", b =>
                {
                    b.Navigation("MaterialConsumptions");

                    b.Navigation("Materials");

                    b.Navigation("ProductBatches");

                    b.Navigation("Steps");
                });
#pragma warning restore 612, 618
        }
    }
}
