// <auto-generated />
using System;
using EquillibriumERP.Manufacturing.Infrastructure.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace EquillibriumERP.Manufacturing.Migrations
{
    [DbContext(typeof(ManufacturingDbContext))]
    partial class ManufacturingDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.7")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("EquillibriumERP.Manufacturing.Domain.Entities.BOMStep", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Action")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid>("BillOfMaterialId")
                        .HasColumnType("uuid");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("DurationMinutes")
                        .HasColumnType("integer");

                    b.Property<int>("Status")
                        .HasColumnType("integer");

                    b.Property<int>("StepNumber")
                        .HasColumnType("integer");

                    b.Property<int>("Type")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("BillOfMaterialId");

                    b.ToTable("BOMSteps", (string)null);
                });

            modelBuilder.Entity("EquillibriumERP.Manufacturing.Domain.Entities.BOMStepMaterial", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("BOMStepId")
                        .HasColumnType("uuid");

                    b.Property<decimal>("Quantity")
                        .HasPrecision(18, 4)
                        .HasColumnType("numeric(18,4)");

                    b.Property<Guid>("RawMaterialProductId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("BOMStepId");

                    b.HasIndex("RawMaterialProductId");

                    b.ToTable("BOMStepMaterials", (string)null);
                });

            modelBuilder.Entity("EquillibriumERP.Manufacturing.Domain.Entities.BillOfMaterial", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid>("ProductId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.ToTable("BillOfMaterials", (string)null);
                });

            modelBuilder.Entity("EquillibriumERP.Manufacturing.Domain.Entities.BillOfMaterialItem", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("BillOfMaterialId")
                        .HasColumnType("uuid");

                    b.Property<decimal>("Quantity")
                        .HasPrecision(18, 4)
                        .HasColumnType("numeric(18,4)");

                    b.Property<Guid>("RawMaterialProductId")
                        .HasColumnType("uuid");

                    b.Property<string>("UnitOfMeasure")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.HasKey("Id");

                    b.HasIndex("BillOfMaterialId");

                    b.ToTable("BillOfMaterialItems", (string)null);
                });

            modelBuilder.Entity("EquillibriumERP.Manufacturing.Domain.Entities.MaterialConsumption", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("ConsumedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("LotNumber")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<decimal>("Quantity")
                        .HasPrecision(18, 4)
                        .HasColumnType("numeric(18,4)");

                    b.Property<Guid>("RawMaterialProductId")
                        .HasColumnType("uuid");

                    b.Property<string>("UnitOfMeasure")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<Guid>("WorkOrderId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("WorkOrderStepId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("LotNumber");

                    b.HasIndex("RawMaterialProductId");

                    b.HasIndex("WorkOrderId");

                    b.HasIndex("WorkOrderStepId");

                    b.ToTable("MaterialConsumptions", (string)null);
                });

            modelBuilder.Entity("EquillibriumERP.Manufacturing.Domain.Entities.ProductBatch", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("BatchNumber")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("ProductId")
                        .HasColumnType("uuid");

                    b.Property<decimal>("QuantityProduced")
                        .HasPrecision(18, 4)
                        .HasColumnType("numeric(18,4)");

                    b.Property<Guid>("WorkOrderId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("BatchNumber");

                    b.HasIndex("WorkOrderId");

                    b.ToTable("ProductBatches", (string)null);
                });

            modelBuilder.Entity("EquillibriumERP.Manufacturing.Domain.Entities.StepMaterialConsumption", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<decimal>("QuantityUsed")
                        .HasPrecision(18, 4)
                        .HasColumnType("numeric(18,4)");

                    b.Property<Guid>("RawMaterialProductId")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("RecordedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("WorkOrderStepId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("RawMaterialProductId");

                    b.HasIndex("WorkOrderStepId");

                    b.ToTable("StepMaterialConsumptions", (string)null);
                });

            modelBuilder.Entity("EquillibriumERP.Manufacturing.Domain.Entities.WorkOrder", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("BillOfMaterialId")
                        .HasColumnType("uuid");

                    b.Property<decimal>("PlannedQuantity")
                        .HasPrecision(18, 4)
                        .HasColumnType("numeric(18,4)");

                    b.Property<int>("Status")
                        .HasColumnType("integer");

                    b.Property<string>("UnitOfMeasure")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.HasKey("Id");

                    b.HasIndex("BillOfMaterialId");

                    b.ToTable("WorkOrders", (string)null);
                });

            modelBuilder.Entity("EquillibriumERP.Manufacturing.Domain.Entities.WorkOrderMaterial", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<decimal>("ConsumedQuantity")
                        .HasPrecision(18, 4)
                        .HasColumnType("numeric(18,4)");

                    b.Property<decimal>("ExpectedQuantity")
                        .HasPrecision(18, 4)
                        .HasColumnType("numeric(18,4)");

                    b.Property<decimal>("IssuedQuantity")
                        .HasPrecision(18, 4)
                        .HasColumnType("numeric(18,4)");

                    b.Property<Guid>("RawMaterialProductId")
                        .HasColumnType("uuid");

                    b.Property<string>("UnitOfMeasure")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<Guid>("WorkOrderId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("WorkOrderId");

                    b.ToTable("WorkOrderMaterials", (string)null);
                });

            modelBuilder.Entity("EquillibriumERP.Manufacturing.Domain.Entities.WorkOrderStep", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Action")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid>("BOMProcessStepId")
                        .HasColumnType("uuid");

                    b.Property<DateTime?>("CompletedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("StartedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("Status")
                        .HasColumnType("integer");

                    b.Property<int>("StepNumber")
                        .HasColumnType("integer");

                    b.Property<Guid>("WorkOrderId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("WorkOrderId");

                    b.ToTable("WorkOrderStep");
                });

            modelBuilder.Entity("EquillibriumERP.Manufacturing.Domain.Entities.BOMStep", b =>
                {
                    b.HasOne("EquillibriumERP.Manufacturing.Domain.Entities.BillOfMaterial", null)
                        .WithMany("Steps")
                        .HasForeignKey("BillOfMaterialId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("EquillibriumERP.Manufacturing.Domain.Entities.BOMStepMaterial", b =>
                {
                    b.HasOne("EquillibriumERP.Manufacturing.Domain.Entities.BOMStep", null)
                        .WithMany()
                        .HasForeignKey("BOMStepId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("EquillibriumERP.Manufacturing.Domain.Entities.BillOfMaterialItem", b =>
                {
                    b.HasOne("EquillibriumERP.Manufacturing.Domain.Entities.BillOfMaterial", "BillOfMaterial")
                        .WithMany("Items")
                        .HasForeignKey("BillOfMaterialId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("BillOfMaterial");
                });

            modelBuilder.Entity("EquillibriumERP.Manufacturing.Domain.Entities.MaterialConsumption", b =>
                {
                    b.HasOne("EquillibriumERP.Manufacturing.Domain.Entities.WorkOrder", "WorkOrder")
                        .WithMany("MaterialConsumptions")
                        .HasForeignKey("WorkOrderId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("EquillibriumERP.Manufacturing.Domain.Entities.WorkOrderStep", "WorkOrderStep")
                        .WithMany()
                        .HasForeignKey("WorkOrderStepId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("WorkOrder");

                    b.Navigation("WorkOrderStep");
                });

            modelBuilder.Entity("EquillibriumERP.Manufacturing.Domain.Entities.ProductBatch", b =>
                {
                    b.HasOne("EquillibriumERP.Manufacturing.Domain.Entities.WorkOrder", "WorkOrder")
                        .WithMany("ProductBatches")
                        .HasForeignKey("WorkOrderId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("WorkOrder");
                });

            modelBuilder.Entity("EquillibriumERP.Manufacturing.Domain.Entities.WorkOrder", b =>
                {
                    b.HasOne("EquillibriumERP.Manufacturing.Domain.Entities.BillOfMaterial", "BillOfMaterial")
                        .WithMany()
                        .HasForeignKey("BillOfMaterialId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("BillOfMaterial");
                });

            modelBuilder.Entity("EquillibriumERP.Manufacturing.Domain.Entities.WorkOrderMaterial", b =>
                {
                    b.HasOne("EquillibriumERP.Manufacturing.Domain.Entities.WorkOrder", "WorkOrder")
                        .WithMany("Materials")
                        .HasForeignKey("WorkOrderId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("WorkOrder");
                });

            modelBuilder.Entity("EquillibriumERP.Manufacturing.Domain.Entities.WorkOrderStep", b =>
                {
                    b.HasOne("EquillibriumERP.Manufacturing.Domain.Entities.WorkOrder", "WorkOrder")
                        .WithMany()
                        .HasForeignKey("WorkOrderId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("WorkOrder");
                });

            modelBuilder.Entity("EquillibriumERP.Manufacturing.Domain.Entities.BillOfMaterial", b =>
                {
                    b.Navigation("Items");

                    b.Navigation("Steps");
                });

            modelBuilder.Entity("EquillibriumERP.Manufacturing.Domain.Entities.WorkOrder", b =>
                {
                    b.Navigation("MaterialConsumptions");

                    b.Navigation("Materials");

                    b.Navigation("ProductBatches");
                });
#pragma warning restore 612, 618
        }
    }
}
